### ISSUE TITLE
Can't find api key on my user profile

### ISSUE THREAD

**Issue by vaibhavkumar049** [brlcad/gciquotient#14]
I want to download my gci data but not able to find API key on my user profile ..

**Comment by brlcad** [comment]
Are you the admin?  It may only be available to admins.  Otherwise, it's simply on the right side of your profile like shown in this screenshot.
<img width="1502" alt="Screen Shot 2020-03-25 at 1 06 06 AM" src="https://user-images.githubusercontent.com/940391/77503809-f3735c80-6e34-11ea-8281-73ad9c2340fe.png">
